package xx入门;

import java.text.ParseException;

public class 异常 {
	
	public static void main(String[] args)  {
		
		
	
		
		try {
			new 异常().trys();
		} catch (Exception e) {
			// TODO 自动生成的 catch 块
			e.printStackTrace();
			
			
			
		}
			
		
		
			
	}
	public void trys() throws Exception 
	{
		int a=15;
		int b=0;

		int c=a/b;
	}

}
